"""
This script is used to denoise the symptoms generated by the small models.
We would like to output is exactly like:
``The severity is approximately xxx. xxx``
or
``Cannot be identified.``
"""
import os
import re
import sys
from tqdm import tqdm
import json
import argparse
from typing import Union, List
from collections import defaultdict

sys.path.append("../../")
from chatarena.message import Message
from llm_utils import OpenLLMChat, llm_response

SYSTEM_PROMPT = "Please refine the given sentence by following these rules:\n\n1. If the symptoms cannot be identified or no severity value is provided (even if symptoms are given), start the sentence with \"Cannot be identified.\"\n2. If there is an exact severity value (an integer) in the sentence, start the sentence with \"The severity is approximately xxx. zzz\". Replace xxx with one and only one severity value extracted from the given sentence, and xxx should not be multiple values or a range. Replace zzz with one-sentence reason for the severity. Don't make up severity values, since you can answer with \"Cannot be identified.\"\n\nBegin your response using \"The severity is approximately\" or \"Cannot be identified.\""


def denoising(
        text: Union[str, List[str]],
        severity: Union[str, List[str]],
        llm_agent: OpenLLMChat,
        batch_size: int = 8
) -> Union[str, List[str]]:
    if isinstance(text, str):
        query_message = Message(
            agent_name="user",
            content=f"The sentence: {text}\n\nAttention: Begin your response using \"The severity is approximately (one integer)\" or \"Cannot be identified.\" And the severity value must be extracted from the sentence if any.",
            turn=-1
        )
        response = llm_response(llm_agent, query_message, SYSTEM_PROMPT)
        return response
    else:
        query_message_batch = [Message(
            agent_name="user",
            content=f"The sentence: {query}\n\nAttention: Begin your response using \"The severity is approximately (one integer)\" or \"Cannot be identified.\" And the severity value must be extracted from the sentence if any.",
            turn=-1
        ) for idx, query in enumerate(text)]
        response_batch = []
        for i in range(0, len(query_message_batch), batch_size):
            query_message_mini_batch = query_message_batch[i:i + batch_size]
            responses = llm_response(llm_agent, query_message_mini_batch, SYSTEM_PROMPT)
            if isinstance(responses, str):
                responses = [responses]
            responses = [response + "." if response[-1] != "." else response for response in responses]
            response_batch.extend(responses)
        return response_batch


if __name__ == "__main__":
    args = argparse.ArgumentParser()
    args.add_argument("--model_name", type=str, default="gpt-3.5-turbo-0125")
    args.add_argument("--input_path", type=str, required=True)
    args.add_argument("--output_path", type=str, default="")
    args = args.parse_args()
    input_files = sorted(os.listdir(args.input_path))
    if not os.path.exists(args.output_path):
        os.makedirs(args.output_path, exist_ok=True)

    llm_agent = OpenLLMChat(model=args.model_name, temperature=0, max_tokens=256)
    severities = json.load(open("../simulated_content/symptoms.json", "r"))
    severity_dict = {
        "PHQ-9": ", ".join([f"{k}: {v}" for k, v in severities["PHQ-9"]["severity"].items()]),
        "GAD-7": ", ".join([f"{k}: {v}" for k, v in severities["GAD-7"]["severity"].items()]),
        "OQ-45-pos": ", ".join([f"{k}: {v}" for k, v in severities["OQ-45"]["positive severity"].items()]),
        "OQ-45-neg": ", ".join([f"{k}: {v}" for k, v in severities["OQ-45"]["negative severity"].items()])
    }
    OQ45_pos = severities["OQ-45"]["positive queries"]
    for file in tqdm(input_files, total=len(input_files)):
        if os.path.exists(os.path.join(args.output_path, file)):
            continue
        denoise_aspects = []
        denoise_indexes = []
        denoise_queries = []
        denoise_severities = []
        predicted_symptoms = json.load(open(os.path.join(args.input_path, file), "r"))
        for aspect, queries in predicted_symptoms.items():
            for query_idx, query in queries.items():
                if query.startswith("The severity is approximately") or query.startswith("Cannot be identified."):
                    continue
                else:
                    denoise_aspects.append(aspect)
                    denoise_indexes.append(query_idx)
                    denoise_queries.append(query)
                    if aspect == "OQ-45" and query_idx in OQ45_pos:
                        denoise_severities.append(severity_dict["OQ-45-pos"])
                    elif aspect == "OQ-45":
                        denoise_severities.append(severity_dict["OQ-45-neg"])
                    else:
                        denoise_severities.append(severity_dict[aspect])
        assert len(denoise_aspects) == len(denoise_indexes) == len(denoise_queries)
        denoise_queries = denoising(denoise_queries, denoise_severities, llm_agent)
        assert len(denoise_queries) == len(denoise_aspects) == len(denoise_indexes)
        for i, aspect in enumerate(denoise_aspects):
            predicted_symptoms[aspect][denoise_indexes[i]] = denoise_queries[i].strip()

        with open(os.path.join(args.output_path, file), "w") as f:
            json.dump(predicted_symptoms, f, indent=4)
